### ISSUE TITLE
This message is not supported in your version of Kotatogram. Please update to the latest version via Settings or install it from https://kotatogram.github.io

### ISSUE THREAD

**Issue by K14Mua** [kotatogram/kotatogram-desktop#408] opened 2022-12-03 12:45 UTC
### Steps to reproduce

Actively use news channels

### Expected behaviour

See and read the news message

### Actual behaviour

"This message is not supported in your version of Kotatogram. Please update to the latest version via Settings or install it from https://kotatogram.github.io"

### Operating system

Windows 10 Pro x64 21H1 (OS 19043.2311)

### Version of Kotatogram Desktop

1.4.9 beta x64 (TD 3.5.2)

### Installation source

Static binary from official website

### Logs

```shell
Is the author going to keep the client in working order or is it time to return to the official client?
```

**Comment by EricKotato** [comment] 2022-12-04 08:31
Duplicate of #399 (and many others). Update will be soon.

**Closed as completed by EricKotato** 2022-12-04 08:31 UTC
