### ISSUE TITLE
Will you upload it to WIndows Store now that its free to do?

### ISSUE THREAD

**Issue by Manasroxx** [kotatogram/kotatogram-desktop#282] opened 2021-12-27 05:28 UTC
This is by far the best Tlgrm client for windows just pls dont go Unigram way adding mica to Kotatogram
Are you thinking of uploading app to Windows store?

**Comment by RadRussianRus** [comment] 2021-12-28 02:48
Where have you found info about "free"? Microsoft site [says it's $19](https://developer.microsoft.com/en-us/microsoft-store/register/):
![](https://user-images.githubusercontent.com/2903496/147521253-7afe5c75-c299-4f33-a999-001b5418cc21.png)

But it's not just about the cost. The problem is that building TDesktop (and subsequently, Kotatogram) is costly in terms of hard drive space and time. Linux and macOS versions are built on GitHub CI, which lifts some of the weight. But Windows version can't be built on CI, so I need to build both 32-bit and 64-bit version on my PC.

Putting it in store means that I need to build at least one, if not two, separate builds, since you must build it for UWP, even though only UWP thing is the .appx packaging. Even when "traditional desktop app publising" will be released, separate builds would still be needed: some channels were restricted in Telegram by Microsoft Store rules, and disabling them could lead to ban in Microsoft Store, leading to time and money loss.

Maybe if I'll try if I'll have a developer account and more hard drive space for this, but until then I don't think it's worth it.

**Closed by RadRussianRus** 2021-12-28 02:48 UTC
Labels: question
