### ISSUE TITLE
Local folder is gone even though it is exist in config file

### ISSUE THREAD

**Issue by ElementalCyclone** [kotatogram/kotatogram-desktop#294] opened 2022-01-20 21:31 UTC
### Steps to reproduce

1. Create a local folder as usual.
2. Verify the folder is there with its content (you can do this by getting in & out from main chat list and folder's chat list).
3. Exit Kotatogram, make sure the app is terminated.
4. Enter Kotatogram again, now the folder is gone.

### Expected behaviour

The local folder should persist between app restart. kotato-settings-custom.json file should 'remember' the local folder(s) and its contents

### Actual behaviour

The local folder will be gone after app restart, even though kotato-settings-custom.json verified to be remember the local folder(s) and its contents (JSON file verified on having "folders" section with "default" and "local" subsection having presumably correct content).

### Operating system

Windows 10 21H1 x64, build 19043.14.15

### Version of Kotatogram Desktop

1.4.8

### Installation source

Static binary from official website

### Logs

```shell
[2022.01.21 04:15:07] Launched version: 3003000, install beta: [FALSE], dev: 0, debug mode: [FALSE]
[2022.01.21 04:15:07] Executable dir: <Kotatogram Installdir>/Kotatogram Desktop/, name: Kotatogram.exe
[2022.01.21 04:15:07] Initial working dir: <Kotatogram Installdir>/Kotatogram Desktop/
[2022.01.21 04:15:07] Working dir: <Kotatogram Installdir>/Kotatogram Desktop/
[2022.01.21 04:15:07] Command line: <Kotatogram Installdir>\Kotatogram Desktop\Kotatogram.exe
[2022.01.21 04:15:07] Executable path before check: <Kotatogram Installdir>/Kotatogram Desktop/Kotatogram.exe
[2022.01.21 04:15:07] Logs started
[2022.01.21 04:15:07] Connecting local socket to Global\7ac2d6b17ef9a71f09c06ea93da8757b-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2022.01.21 04:15:07] This is the only instance of Telegram, starting server and app...
[2022.01.21 04:15:07] Moved logging from '<Kotatogram Installdir>/Kotatogram Desktop/log_start0.txt' to '<Kotatogram Installdir>/Kotatogram Desktop/log.txt'!
[2022.01.21 04:15:07] Primary screen DPI: 96
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.01.21 04:15:07] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.01.21 04:15:07] Using DirectX compiler '<Kotatogram Installdir>\Kotatogram Desktop\modules\x64\d3d\d3dcompiler_47.dll'.
[2022.01.21 04:15:07] App Info: reading settings...
[2022.01.21 04:15:07] App Info: reading encrypted settings...
[2022.01.21 04:15:07] Lang Info: Loaded cached, keys: 3570
[2022.01.21 04:15:07] OpenAL Logging Level: (not set)
[2022.01.21 04:15:07] Audio Playback Devices: OpenAL Soft on Speakers / Headphones (Realtek Audio)
[2022.01.21 04:15:07] Audio Playback Default Device: OpenAL Soft on Speakers / Headphones (Realtek Audio)
[2022.01.21 04:15:07] Audio Capture Devices: OpenAL Soft on Microphone (Realtek Audio)
[2022.01.21 04:15:07] Audio Capture Default Device: OpenAL Soft on Microphone (Realtek Audio)
[2022.01.21 04:15:07] App Info: reading accounts info...
[2022.01.21 04:15:07] App Info: reading encrypted info...
[2022.01.21 04:15:07] App Info: reading map...
[2022.01.21 04:15:07] App Info: reading encrypted map...
[2022.01.21 04:15:07] App Info: reading encrypted user settings...
[2022.01.21 04:15:07] App Info: encrypted user settings read.
[2022.01.21 04:15:07] App Info: reading encrypted mtp data...
[2022.01.21 04:15:07] MTP Info: read keys, current: 4, to destroy: 0
[2022.01.21 04:15:07] Map read time: 1
[2022.01.21 04:15:07] App Info: reading encrypted mtp config...
[2022.01.21 04:15:08] Export Info: Destroy top bar by controller removal.
[2022.01.21 04:15:08] OpenGL: Using custom 'gpu_driver_bug_list.json'.
[2022.01.21 04:15:08] OpenGL Profile: OpenGLES.
[2022.01.21 04:15:08] OpenGL Renderer: ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.4531)
[2022.01.21 04:15:08] OpenGL Vendor: Google Inc. (Intel)
[2022.01.21 04:15:08] OpenGL Version: OpenGL ES 3.0.0 (ANGLE 2.1.7 git hash: 0bb011f9e403)
[2022.01.21 04:15:08] OpenGL Extensions: GL_ANGLE_memory_size, GL_EXT_debug_marker, GL_OES_EGL_image, GL_OES_texture_stencil8, GL_ANGLE_get_tex_level_parameter, GL_ANGLE_provoking_vertex, GL_EXT_robustness, GL_EXT_unpack_subimage, GL_EXT_texture_storage, GL_ANGLE_client_arrays, GL_OES_compressed_EAC_R11_unsigned_texture, GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture, GL_OES_EGL_image_external_essl3, GL_ANGLE_depth_texture, GL_OES_draw_buffers_indexed, GL_OES_depth32, GL_EXT_texture_format_BGRA8888, GL_ANGLE_texture_multisample, GL_EXT_draw_buffers, GL_WEBGL_video_texture, GL_OES_draw_elements_base_vertex, GL_EXT_EGL_image_external_wrap_modes, GL_EXT_occlusion_query_boolean, GL_OES_surfaceless_context, GL_ANGLE_texture_usage, GL_OES_mapbuffer, GL_ANGLE_texture_compression_dxt5, GL_KHR_parallel_shader_compile, GL_ANGLE_request_extension, , GL_CHROMIUM_copy_texture, GL_NV_pixel_buffer_object, GL_ANGLE_framebuffer_multisample, GL_OES_texture_npot, GL_EXT_texture_filter_anisotropic, GL_OES_texture_half_float, GL_ANGLE_base_vertex_base_instance, GL_EXT_texture_rg, GL_OES_fbo_render_mipmap, GL_CHROMIUM_sync_query, GL_ANGLE_copy_texture_3d, GL_EXT_texture_norm16, GL_OES_compressed_ETC2_RGBA8_texture, GL_EXT_color_buffer_half_float, GL_OES_compressed_EAC_RG11_unsigned_texture, GL_ANGLE_robust_client_memory, GL_NV_EGL_stream_consumer_external, GL_NV_pack_subimage, GL_OES_rgb8_rgba8, GL_ANGLE_translated_shader_source, GL_EXT_draw_elements_base_vertex, GL_EXT_texture_compression_s3tc_srgb, GL_EXT_sRGB, GL_ANGLE_get_serialized_context_string, GL_CHROMIUM_bind_uniform_location, GL_EXT_color_buffer_float, GL_ANGLE_multi_draw, GL_OES_standard_derivatives, GL_OES_compressed_ETC2_sRGB8_alpha8_texture, GL_OES_EGL_image_external, GL_OVR_multiview2, GL_OVR_multiview, GL_EXT_float_blend, GL_OES_texture_half_float_linear, GL_ANGLE_framebuffer_blit, GL_CHROMIUM_bind_generates_resource, GL_ANGLE_explicit_context, GL_OES_compressed_EAC_R11_signed_texture, GL_ANGLE_lossy_etc_decode, GL_OES_compressed_ETC2_sRGB8_texture, GL_EXT_shader_texture_lod, GL_OES_compressed_EAC_RG11_signed_texture, GL_ANGLE_pack_reverse_row_order, GL_ANGLE_program_cache_control, GL_EXT_read_format_bgra, GL_EXT_disjoint_timer_query, GL_EXT_texture_compression_bptc, GL_OES_texture_float, GL_OES_vertex_array_object, GL_EXT_instanced_arrays, GL_OES_get_program_binary, GL_ANGLE_multiview_multisample, GL_NV_fence, GL_EXT_multisampled_render_to_texture, GL_CHROMIUM_lose_context, GL_EXT_texture_compression_rgtc, GL_EXT_draw_buffers_indexed, GL_CHROMIUM_copy_compressed_texture, GL_EXT_discard_framebuffer, GL_EXT_blend_func_extended, GL_ANGLE_explicit_context_gles1, GL_EXT_map_buffer_range, GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture, GL_ANGLE_texture_compression_dxt3, GL_EXT_blend_minmax, GL_KHR_debug, GL_OES_texture_float_linear, GL_OES_depth24, GL_OES_compressed_ETC2_RGB8_texture, GL_OES_element_index_uint, GL_OES_packed_depth_stencil, GL_OES_texture_border_clamp, GL_EXT_debug_label, GL_EXT_texture_compression_dxt1, GL_ANGLE_instanced_arrays, GL_EXT_frag_depth
[2022.01.21 04:15:08] EGL Extensions: EGL_EXT_create_context_robustness, EGL_ANGLE_d3d_share_handle_client_buffer, EGL_ANGLE_d3d_texture_client_buffer, EGL_ANGLE_surface_d3d_texture_2d_share_handle, EGL_ANGLE_query_surface_pointer, EGL_ANGLE_window_fixed_size, EGL_ANGLE_keyed_mutex, EGL_ANGLE_surface_orientation, EGL_ANGLE_direct_composition, EGL_ANGLE_windows_ui_composition, EGL_NV_post_sub_buffer, EGL_KHR_create_context, EGL_KHR_image, EGL_KHR_image_base, EGL_KHR_gl_texture_2D_image, EGL_KHR_gl_texture_cubemap_image, EGL_KHR_gl_renderbuffer_image, EGL_KHR_get_all_proc_addresses, EGL_KHR_stream, EGL_KHR_stream_consumer_gltexture, EGL_NV_stream_consumer_gltexture_yuv, EGL_ANGLE_flexible_surface_compatibility, EGL_ANGLE_stream_producer_d3d_texture, EGL_ANGLE_create_context_webgl_compatibility, EGL_CHROMIUM_create_context_bind_generates_resource, EGL_CHROMIUM_sync_control, EGL_EXT_pixel_format_float, EGL_KHR_surfaceless_context, EGL_ANGLE_display_texture_share_group, EGL_ANGLE_display_semaphore_share_group, EGL_ANGLE_create_context_client_arrays, EGL_ANGLE_program_cache_control, EGL_ANGLE_robust_resource_initialization, EGL_ANGLE_create_context_extensions_enabled, EGL_ANDROID_blob_cache, EGL_ANDROID_recordable, EGL_ANGLE_image_d3d11_texture, EGL_ANGLE_create_context_backwards_compatible, EGL_KHR_create_context_no_error, EGL_KHR_reusable_sync, 
[2022.01.21 04:15:08] OpenGL: QOpenGLContext created, version: 3.3.
[2022.01.21 04:15:08] OpenGL: [TRUE] (OverlayWidget)
[2022.01.21 04:15:12] API Warning: not loaded minimal channel applied.
[2022.01.21 04:15:12] API Warning: not loaded minimal channel applied.
[2022.01.21 04:16:14] API Warning: not loaded minimal channel applied.
[2022.01.21 04:16:36] API Warning: not loaded minimal channel applied.
[2022.01.21 04:20:26] API Warning: not loaded minimal channel applied.
[2022.01.21 04:21:13] API Warning: not loaded minimal channel applied.
[2022.01.21 04:21:13] API Warning: not loaded minimal channel applied.
```

### Aditional Information

1. Installation dir is not in the default AppData/Roaming directory in C:, but somewhere else and not in the C:'s sub-directories.
2. Beside the local folder, there's no cloud/account synced folder.

**Comment by EricKotato** [comment] 2022-01-22 00:58
Can't reproduce it, sadly.

**Comment by ElementalCyclone** [comment] 2022-01-22 13:24
> Can't reproduce it, sadly.

Huh, that's weird, I'm retesting it in case it is a weird, one time behavior, but no, the result is consistent. I even tried if one of the factor is because i don't have any cloud folder, but the result is still the same. With both cloud folder exist and not prior to the repro steps, the result is still the same.

Also, i found additional behavior that i just realized. When i am repro-ing it, the first time i am opening the client after creating and closing the client, the Window adds space on its left when loading for the chats, the space where usually folders icons reside, indicating it do knows that there's "Folder", but right before the chats are shown, the space is gone.

Regarding that, is there any probability that something silently gone fail or because the verbosity is set not high enough, it didn't get logged ? is there any way for me to switch up the log's verbosity level ?

**Comment by EricKotato** [comment] 2022-01-22 13:29
>Huh, that's weird, I'm retesting it in case it is a weird, one time behavior, but no, the result is consistent.

Hm. That's a wild guess, but does your folder contain chats with IDs higher than signed 32-bit integer upper limit?

**Comment by EricKotato** [comment] 2022-01-22 13:31
>is there any way for me to switch up the log's verbosity level ?

There are no debug logs for local folders currently, sadly.

**Comment by ElementalCyclone** [comment] 2022-01-22 15:48
> does your folder contain chats with IDs higher than signed 32-bit integer upper limit?

After checking it, sadly it isnt. The signed int32 upper limit is 2147483647 and the channel's ID number is on 148xxxxxxx
range.

Ah yes, another piece information i forgot to add is, i only repro it with channels, i've never tried groups or personal chats.

**Comment by ElementalCyclone** [comment] 2022-01-28 01:32
So, regarding this local folder issue, is there any other things or place i need to check ? maybe other config or log file i can provide ?

**Comment by EricKotato** [comment] 2022-01-28 10:02
I suggest to wait until next update. Since I'm doing internal rework of Kotatogram Settings (including local folders), maybe it could fix the issue.

**Comment by the-blank-x** [comment] 2022-02-02 15:31
Does your user id have more than 32-bits?

**Comment by ElementalCyclone** [comment] 2022-02-03 03:24
> Does your user id have more than 32-bits?

after checking it, yes, my user ID is even bigger than unsigned int32

**Comment by EricKotato** [comment] 2022-02-14 21:20
Should be fixed by https://github.com/kotatogram/kotatogram-desktop/commit/845957f33aea4aac7038a9fac0e5e6321b13fcb6.

**Closed as completed by EricKotato** 2022-02-14 21:20 UTC
