### ISSUE TITLE
[Question] Any plans for Secret Chats?

### ISSUE THREAD

**Issue by macruspareto** [kotatogram/kotatogram-desktop#245] opened 2021-10-23 16:16 UTC
Great fork, guys, and is worth replacing the official client!

Got a question: Ever considered adding Secret Chats ?
The desktop version for MacOS has it for years now.
This fork for Win10 also has it - https://github.com/UnigramDev/Unigram

I see no technical obstacles for not adding it. TG Official team is still in denial and I don't know why. It's not a 'security' issue but rather some ideological reason.

Implementing it would give a huge market advantage and recognition. All the best from Italy!

**Comment by RadRussianRus** [comment] 2021-11-02 12:36
Duplicate of #8.

**Closed by RadRussianRus** 2021-11-02 12:36 UTC
Labels: question
